<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>index</title>

    <link rel="stylesheet" href="css/bootstrap.min.css">
    <style>
        .wrap{
            padding-top:20px;
            padding-left:15px;
        }
        #div1{
            font-size:15px;
            color:#999;
        }
        #div2{
            margin:40px auto;
            text-align:center;
        }
        #div2>div{
            width:200px;
            height:200px;
            border:1px solid #000000;
            border-radius:5px;
            margin:0 auto;
        }
        #div2>div>img{
            width:200px;
            height:200px;
            border:1px solid #000000;
            border-radius:5px;
            margin:0 auto;
        }
        #div2>h4{
            color:#5cb85c;
        }
        #div2>p{
            margin-top:15px;
            font-size:15px;
            color:#999;
        }
        #div2>p>span{
            color:#5cb85c;
        }
        #div3{
            padding-top:100px;
        }
    </style>
</head>
<body class="container">
<div class="row">
    <div class="col-xs-12 wrap">
       <div id="div1">充值类型选择</div>
        <div id="div2">
            <h4>快汇宝支付</h4>
            <div id="icon"><img src="img/icon.png" alt=""></div>
            <p>当前充值：<span id="amount"></span>&nbsp;元</p>
            <p>用户ID：<span id="userid"></span></p>
        </div>
        <div id="div3">
            <h5>操作说明：</h5>
            使用微信扫描或识别二维码进行付款操作；<br>
            备注需要填写玩家ID，以便记录充值；
        </div>
    </div>
</div>


</body>

<script src="js/jquery-1.11.3.js"></script>
<script src="js/bootstrap.min.js"></script>
<script>
    var amount = location.search.split('&')[0].split('=')[1];
    var user_id = location.search.split('&')[1].split('=')[1];
    $("#userid").val(user_id);
    $("#amount").val(amount);
</script>
</html>