<?php include_once VIEW_COMMON."header.php"; ?>
<div class="main-container" id="main-container" style="margin-left: 0px;">
    <div class="main-container-inner">
        <div class="main-content">
        <div class="page-content">
            <div class="row">
                <div class="col-xs-12">
                    <form class="form-horizontal" id="form">
                        <input type="hidden" id="id" value="<?php echo $info ? $info['id'] : 0?>">
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">新密码：</label>
                            <div class="col-sm-10 mt5">
                                <input type="text" id="newpwd" name="pwd"
                                       class="col-sm-5" value=''>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">重置保险箱密码：</label>
                            <div class="col-sm-10">
                                <a href="/player/user/resafe?id=<?php echo $info ? $info['id'] : 0?>">前往重置</a>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">冻结账户：</label>
                            <div class="col-sm-10">
                                <a href="/player/user/stock?id=<?php echo $info ? $info['id'] : 0?>">前往冻结</a>
                            </div>
                        </div>

                        </div>
                        
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button class="btn btn-primary" type="submit" id="save">
                                    <i class="icon-ok"></i>
                                    保存
                                </button>
                                <a class="btn" href="/player/user/info?id=<?php echo $info ? $info['id'] : 0?>">
                                    <i class="icon-undo"></i>
                                    取消
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
<?php include_once VIEW_COMMON."footer.php"; ?>
<link rel="stylesheet" href="/skin/umeditor/themes/default/css/umeditor.css" />
<script src="/skin/umeditor/umeditor.config.js"></script>
<script src="/skin/umeditor/umeditor.min.js"></script>
<script src="/skin/js/jquery.validate.min.js"></script>
<link rel="stylesheet" href="/skin/css/daterangepicker.css" />
<script src="/skin/js/moment.min.js"></script>
<script src="/skin/js/daterangepicker.min.js"></script>
<script type="text/javascript">
    $(function () {
        var cnt = UM.getEditor('editer', ace.editorConfig);
        $('#avttime').daterangepicker({
            singleDatePicker: true,
            timePicker: !0,
            format: "YYYY/MM/DD HH:mm"
        });
        $('.inimage').InsertImage();
        $("#form").validate({
            errorElement: "span",
            highlight: function (element, errorClass, validClass) {
                $(element).parents('.form-group').addClass('has-error');
            },
            unhighlight: function (element, errorClass, validClass) {
                $(element).parents('.form-group').removeClass('has-error');
            },
            submitHandler: function (form)
            {
                var params = {};
                params.id = $('#id').val();
                params.newpwd = $("#newpwd").val();
                $('#save').html('<i class="icon-ok"></i>保存中...').attr('disabled', 'true');
                $.ajax({
                    type: "POST",
                    url: "/player/user/savepwd",
                    data: params,
                    dataType: "json",
                    success: function (msg) {
                        $('#save').html('<i class="icon-ok"></i> 保存').removeAttr('disabled');
                        if (msg.result == 0) {
                            showMsg("成功", function () {
                                window.location.reload();
                                //history.go(-1);
                            });
                        } else {
                            showMsg(msg.message, true);
                        }
                    }
                });
            }
        });
    })
</script>