<?php include_once VIEW_COMMON . "header.php"; ?>
<style>
    .agent{
        width:400px;
        border: 1px #eeeeee solid;
        padding:10px 5px;
        margin:5px 0px;
        background-color: #eeeeee;
    }
    .form-group.has-error .error{
        float: none !important;
    }
</style>
<div class="main-container" id="main-container" style="margin-left: 0px;">
    <div class="main-container-inner">
        <div class="main-content">
            <div class="page-content">
                <div class="row">
                    <div class="col-xs-12">
                        <form class="form-horizontal" id="form">
                            <input type="hidden" id="id" value="<?php echo $info ? $info['id'] : 0?>">
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-right">vip等级或者天数：</label>
                                <div class="col-sm-10">
                                    <input type="text" id="vip_level" readonly class="col-xs-10 col-sm-5" value='<?php echo $info['vip_level']?>'>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-right">每日签到奖励：</label>
                                <div class="col-sm-10">
                                    <input type="text" id="sign_gold" name="sign_gold" 
                                           class="col-xs-10 col-sm-5" value='<?php echo $info['sign_gold'];?>'>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-right">付费：</label>
                                <div class="col-sm-10">
                                    <input type="text" id="vip_pay" name="vip_pay" 
                                           class="col-xs-10 col-sm-5" value='<?php echo $info['vip_pay'];?>'>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-right">vip签到奖励倍数：</label>
                                <div class="col-sm-10">
                                    <input type="text" id="gold_times" name="gold_times" 
                                           class="col-xs-10 col-sm-5" value='<?php echo $info['gold_times'];?>'>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-right">特权金币奖励：</label>
                                <div class="col-sm-10">
                                    <input type="text" id="day_gold" name="day_gold" 
                                           class="col-xs-10 col-sm-5" value='<?php echo $info['day_gold'];?>'>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-right">特权绿宝石奖励：</label>
                                <div class="col-sm-10">
                                    <input type="text" id="emerald" name="emerald" 
                                           class="col-xs-10 col-sm-5" value='<?php echo $info['emerald'];?>'>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-right">特权冰封道具奖励：</label>
                                <div class="col-sm-10">
                                    <input type="text" id="frozen" name="frozen" 
                                           class="col-xs-10 col-sm-5" value='<?php echo $info['frozen'];?>'>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-right">特权鹰眼道具奖励：</label>
                                <div class="col-sm-10">
                                    <input type="text" id="eagleeye" name="eagleeye" 
                                           class="col-xs-10 col-sm-5" value='<?php echo $info['eagleeye'];?>'>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <button class="btn btn-primary" type="submit" id="save">
                                        <i class="icon-ok"></i>
                                        保存
                                    </button>
                                    <a class="btn" href="javascript:history.go(-1);">
                                        <i class="icon-undo"></i>
                                        取消
                                    </a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include_once VIEW_COMMON . "footer.php"; ?>
<link rel="stylesheet" href="/skin/umeditor/themes/default/css/umeditor.css" />
<script src="/skin/umeditor/umeditor.config.js"></script>
<script src="/skin/umeditor/umeditor.min.js"></script>
<script src="/skin/js/jquery.validate.min.js"></script>
<link rel="stylesheet" href="/skin/css/daterangepicker.css" />
<script src="/skin/js/moment.min.js"></script>
<script src="/skin/js/daterangepicker.min.js"></script>
<script type="text/javascript">
    $(function () {
        
        $("#form").validate({
            rules: {
                vip_pay: {
                    required: true,
                    number:true
                },
                sign_gold: {
                    required: true,
                    number:true
                },
                gold_times: {
                    required: true,
                    number:true
                },
                day_gold: {
                    required: true,
                    number:true
                },
                emerald: {
                    required: true,
                    number:true
                },
                frozen: {
                    required: true,
                    number:true
                },
                eagleeye: {
                    required: true,
                    number:true
                }
            },
            messages: {
                vip_pay: {
                    required: '不可为空',
                    number: '请输入整数'
                },
                sign_gold: {
                    required: '不可为空',
                    number: '请输入整数'
                },
                gold_times: {
                    required: '不可为空',
                    number: '请输入整数'
                },
                day_gold: {
                    required: '不可为空',
                    number: '请输入整数'
                },
                emerald: {
                    required: '不可为空',
                    number: '请输入整数'
                },
                frozen: {
                    required: '不可为空',
                    number: '请输入整数'
                },
                eagleeye: {
                    required: '不可为空',
                    number: '请输入整数'
                }
            },
            errorElement: "span",
            highlight: function (element, errorClass, validClass) {
                $(element).parents('.form-group').addClass('has-error');
            },
            unhighlight: function (element, errorClass, validClass) {
                $(element).parents('.form-group').removeClass('has-error');
            },
            submitHandler: function (form)
            {
                var params = {};
                params.id = $("#id").val();
                params.vip_level = $("#vip_level").val();
                params.vip_pay = $("#vip_pay").val();
                params.sign_gold = $("#sign_gold").val();
                params.gold_times = $("#gold_times").val();
                params.day_gold = $("#day_gold").val();
                params.emerald = $("#emerald").val();
                params.frozen = $("#frozen").val();
                params.eagleeye = $("#eagleeye").val();
                $('#save').html('<i class="icon-ok"></i>保存中...').attr('disabled', 'true');
                $.ajax({
                    type: "POST",
                    url: "/gamemt/vip/save",
                    data: params,
                    dataType: "json",
                    success: function (msg) {
                        $('#save').html('<i class="icon-ok"></i> 保存').removeAttr('disabled');
                        if (msg.result == 0) {
                            showMsg("成功", function () {
                                history.go(-1);
                            });
                        } else {
                            showMsg(msg.msg, true);
                        }
                    }
                });
            }
        });
    })
</script>