<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>vip和签到管理</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/css/theme.css">
    <link rel="stylesheet" type="text/css" href="/css/main.css">
    <link rel="stylesheet" type="text/css" href="/css/tables.css" />
    <script type="text/javascript" src="/js/jquery.js"></script>
    <script type="text/javascript" src="/js/bootstrap.js"></script>
    <script type="text/javascript" src="/js/j.dt.min.js"></script>
    <script type="text/javascript" src="/js/moment.js"></script>
    <script type="text/javascript" src="/js/mos.js"></script>
    <script src="/skin/js/bootbox.min.js"></script>
    <style>
        table#tab input,table#tab textarea{
            margin-top:5px;
        }
        table#tab td{ height: 70px;text-align: left !important;}
        table#tab .pad-l{padding-left:30px;}
        table#tab .sel{float:left; border-radius:0px; margin-bottom:5px; max-width:200px; margin-right:30px;}
        table#tab .wid{width:100px; margin:0 10px 5px 0; float:left; vertical-align:middle;}
        table#tab .delspan{cursor:pointer; font-size:12px; font-weight:normal;}
        table#tab td.seltd{ border: 1px solid #ccc;}
        table#tab div.box{ max-height:150px; overflow-y:auto; padding:10px 0 5px 10px;}
        table#tab span.inser{border: 1px solid #ccc; font-size:12px; padding:3px 10px; float:right; cursor:pointer;}
        table#tab textarea.tex{ height:70px; line-height:20px;  padding:5px 7px; resize:none; border-radius:0px;}
        .theadtbody{text-align: left !important;}
        .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td{
            vertical-align: text-bottom !important;
        }
    </style>
</head>

<body class="" style="background: #FFFFFF;">
<div class="header">
    <h1 class="page-title">vip和签到管理</h1>
</div>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="block span6 dataTables_wrapper">
            <table class="table display block-body collapse in" id="example">
                <input type="button" name="btnadd" id="btnadd" onclick="window.location.reload()" class="input_btn_h input-table" value="刷新" />
                <thead class="theadtbody">
                    <tr>
                        <th>vip等级或者天数</th>
                        <th>每日签到奖励</th>
                        <th>vip付费</th>
                        <th>vip签到翻倍</th>
<!--                        <th>vip每日特权奖励</th>-->
                        <th>管理</th>
                    </tr>
                </thead>
                <tbody class="theadtbody">
                    <?php if($list):?>
                    <?php foreach ($list as $k=>$v):?>
                    <tr role='row' class='odd'>
                        <td><?php echo $v['vip_level']?></td>
                        <td><?php echo $v['sign_gold']?>金币</td>
                        <td><?php echo $v['vip_pay']?>元</td>
                        <td><?php echo $v['gold_times']?>倍</td>
<!--                        <td>-->
<!--                            金币:--><?php //echo $v['day_gold'];?><!--<br>-->
<!--                            绿宝石:--><?php //echo $v['emerald'];?><!--<br>-->
<!--                            冰粉道具:--><?php //echo $v['frozen'];?><!--<br>-->
<!--                            鹰眼道具:--><?php //echo $v['eagleeye'];?>
<!--                        </td>-->
                        <td>
                            <button data-ctrl-btn="editAction" onclick="window.location.href='/gamemt/vip/edit?id=<?php echo $v['id'];?>'">编辑</button>
                        </td>
                    </tr>
                    <?php endforeach;?>
                    <?php else:?>
                    <tr role='row' class='odd'>
                        <td colspan="10" style="text-align:center;" >暂无信息</td>
                    </tr>
                    <?php endif;?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<footer><hr></footer>
</body>

</html>

<script src="/js/jquery.form.js"></script>
<script type="text/javascript" src="/js/bootstrap.minv3.js"></script>
<script type="text/javascript" src="/js/bootstrap-dialog.min.js"></script>
<script type="text/javascript" src="/js/main.js"></script>
<script type="text/javascript" src="/js/date.js"></script>

<script type="text/javascript">
    function downAction() {
        doPost('/gamemt/task/update', {'status':0});
    }
    
    function deleteAction() {
        doPost('/gamemt/task/delete');
    }
    
    function upAction() {
        doPost('/gamemt/task/update', {'status':1});
    }
    
    function doPost(url, params={}){
        var list = [];
        $('input[name=line-check]:checked').each(function () {
            list.push(this.value);
        });
        if (list.length == 0) {
            showMsg("请选择要操作的选项", true);
            return;
        }
        params['id'] = list;
        $.post(url, params, function (json) {
            if (json.result == 0) {
                showMsg('修改成功', function(){
                    window.location.reload();
                });
            } else {
                showMsg(json.msg, true);
            }
        }, 'json');
    }
</script>