<?php include_once VIEW_COMMON."header.php"; ?>
<div class="main-container" id="main-container" style="margin-left: 0px;">
    <div class="main-container-inner">
        <div class="main-content">
        <div class="page-content">
            <div class="row">
                <div class="col-xs-12">
                    <form class="form-horizontal" id="form">
                        <input type="hidden" id="id" value="<?php echo $info ? $info['id'] : 0?>">
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">新玩家首次受邀请领取的金币：</label>
                            <div class="col-sm-10">
                                <input type="text" id="new_gold" name="new_gold" 
                                       class="col-xs-10 col-sm-5" value='<?php echo $info ? $info['new_gold'] : ''?>'>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">新玩家领取金币的有效期(单位小时)：</label>
                            <div class="col-sm-10">
                                <input type="text" id="new_time_limit" name="new_time_limit" 
                                       class="col-xs-10 col-sm-5" value='<?php echo $info ? $info['new_time_limit'] : ''?>'>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">新玩家需要游戏次数即可领取：</label>
                            <div class="col-sm-10">
                                <input type="text" id="new_match" name="new_match" 
                                       class="col-xs-10 col-sm-5" value='<?php echo $info ? $info['new_match'] : ''?>'>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">老玩家分享获取的金币：</label>
                            <div class="col-sm-10">
                                <input type="text" id="old_share_gold" name="old_share_gold" 
                                       class="col-xs-10 col-sm-5" value='<?php echo $info ? $info['old_share_gold'] : ''?>'>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">老玩家分享获取金币的时间间隔(单位小时)：</label>
                            <div class="col-sm-10">
                                <input type="text" id="old_share_interval" name="old_share_interval" 
                                       class="col-xs-10 col-sm-5" value='<?php echo $info ? $info['old_share_interval'] : ''?>'>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">老玩家邀请成功一个获取的金币：</label>
                            <div class="col-sm-10">
                                <input type="text" id="old_share_succ" name="old_share_succ" 
                                       class="col-xs-10 col-sm-5" value='<?php echo $info ? $info['old_share_succ'] : ''?>'>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">邀请好友关联的有效期 0表示永远有效 单位小时：</label>
                            <div class="col-sm-10">
                                <input type="text" id="invite_valid_time" name="invite_valid_time" 
                                       class="col-xs-10 col-sm-5" value='<?php echo $info ? $info['invite_valid_time'] : ''?>'>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">邀请url：</label>
                            <div class="col-sm-10">
                                <input type="text" id="invite_url" name="invite_url" 
                                       class="col-xs-10 col-sm-5" value='<?php echo $info ? $info['invite_url'] : ''?>'>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button class="btn btn-primary" type="submit" id="save">
                                    <i class="icon-ok"></i>
                                    保存
                                </button>
                                <a class="btn" href="javascript:history.go(-1);">
                                    <i class="icon-undo"></i>
                                    取消
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
<?php include_once VIEW_COMMON."footer.php"; ?>
<link rel="stylesheet" href="/skin/umeditor/themes/default/css/umeditor.css" />
<script src="/skin/umeditor/umeditor.config.js"></script>
<script src="/skin/umeditor/umeditor.min.js"></script>
<script src="/skin/js/jquery.validate.min.js"></script>
<link rel="stylesheet" href="/skin/css/daterangepicker.css" />
<script src="/skin/js/moment.min.js"></script>
<script src="/skin/js/daterangepicker.min.js"></script>
<script type="text/javascript">
    $(function () {
        $("#form").validate({
            rules: {
                new_gold: {
                    required: true,
                    number: true
                },
                new_time_limit: {
                    required: true,
                    number:true
                },
                new_match: {
                    required: true,
                    number:true
                },
                old_share_gold: {
                    required: true,
                    number:true
                },
                old_share_interval: {
                    required: true,
                    number:true
                },
                old_share_succ: {
                    required: true,
                    number:true
                },
                invite_valid_time: {
                    required: true,
                    number:true
                },
                invite_url: {
                    required: true
                }
            },
            messages: {
                new_gold: {
                    required: '不可为空',
                    number: '请输入整数'
                },
                new_time_limit: {
                    required: '不可为空',
                    number:'请输入整数'
                },
                new_match: {
                    required: '不可为空',
                    number:'请输入整数'
                },
                old_share_gold: {
                    required: '不可为空',
                    number:'请输入整数'
                },
                old_share_interval: {
                    required: '不可为空',
                    number:'请输入整数'
                },
                old_share_succ: {
                    required: '不可为空',
                    number:'请输入整数'
                },
                invite_valid_time: {
                    required: '不可为空',
                    number:'请输入整数'
                },
                invite_url: {
                    required: '不可为空'
                }
            },
            errorElement: "span",
            highlight: function (element, errorClass, validClass) {
                $(element).parents('.form-group').addClass('has-error');
            },
            unhighlight: function (element, errorClass, validClass) {
                $(element).parents('.form-group').removeClass('has-error');
            },
            submitHandler: function (form)
            {
                var params = {};
                params.id = $('#id').val();
                params.new_gold = $('#new_gold').val();
                params.new_time_limit = $('#new_time_limit').val();
                params.new_match = $('#new_match').val();
                params.old_share_gold = $('#old_share_gold').val();
                params.old_share_interval = $('#old_share_interval').val();
                params.old_share_succ = $('#old_share_succ').val();
                params.invite_valid_time = $('#invite_valid_time').val();
                params.invite_url = $('#invite_url').val();
                
                $('#save').html('<i class="icon-ok"></i>保存中...').attr('disabled', 'true');
                $.ajax({
                    type: "POST",
                    url: "/gamemt/share/save",
                    data: params,
                    dataType: "json",
                    success: function (msg) {
                        $('#save').html('<i class="icon-ok"></i> 保存').removeAttr('disabled');
                        if (msg.result == 0) {
                            showMsg("成功", function () {
                                history.go(-1);
                            });
                        } else {
                            showMsg(msg.message, true);
                        }
                    }
                });
            }
        });
    })
</script>