<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>分享管理</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/css/theme.css">
    <link rel="stylesheet" type="text/css" href="/css/main.css">
    <link rel="stylesheet" type="text/css" href="/css/tables.css" />
    <script type="text/javascript" src="/js/jquery.js"></script>
    <script type="text/javascript" src="/js/bootstrap.js"></script>
    <script type="text/javascript" src="/js/j.dt.min.js"></script>
    <script type="text/javascript" src="/js/moment.js"></script>
    <script type="text/javascript" src="/js/mos.js"></script>
    <script src="/skin/js/bootbox.min.js"></script>
    <style>
        table#tab input,table#tab textarea{
            margin-top:5px;
        }
        table#tab td{ height: 70px;text-align: left !important;}
        table#tab .pad-l{padding-left:30px;}
        table#tab .sel{float:left; border-radius:0px; margin-bottom:5px; max-width:200px; margin-right:30px;}
        table#tab .wid{width:100px; margin:0 10px 5px 0; float:left; vertical-align:middle;}
        table#tab .delspan{cursor:pointer; font-size:12px; font-weight:normal;}
        table#tab td.seltd{ border: 1px solid #ccc;}
        table#tab div.box{ max-height:150px; overflow-y:auto; padding:10px 0 5px 10px;}
        table#tab span.inser{border: 1px solid #ccc; font-size:12px; padding:3px 10px; float:right; cursor:pointer;}
        table#tab textarea.tex{ height:70px; line-height:20px;  padding:5px 7px; resize:none; border-radius:0px;}
        .theadtbody{text-align: left !important;}
        .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td{
            vertical-align: text-bottom !important;
        }
    </style>
</head>

<body class="" style="background: #FFFFFF;">
<div class="header">
    <h1 class="page-title">分享管理</h1>
</div>
<ul id="myTab" class="nav nav-tabs">
    <li class="active">
        <a href="/gamemt/share/list">邀请记录</a>
    </li>
    <li>
        <a href="/gamemt/share/edit">分享设置</a>
    </li>
</ul>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="block span6 dataTables_wrapper">
            <table class="table display block-body collapse in" id="example">
                <thead class="theadtbody">
                    <tr>
                        <th>邀请日期</th>
                        <th>邀请人id</th>
                        <th>用户id</th>
                        <th>金币数</th>
                        <th>状态</th>
                        <th>ip地址</th>
                    </tr>
                </thead>
                <tbody class="theadtbody">
                    <?php if($list):?>
                    <?php foreach ($list as $k=>$v):?>
                    <tr role='row' class='odd'>
                        <td><img src="<?php echo date('Y-m-d H:i:s', $v['c_time'])?>" style="width:80px;"></td>
                        <td><?php echo $v['invite_id']?></td>
                        <td><?php echo $v['user_id']?></td>
                        <td><?php echo $v['gold']?></td>
                        <td><?php echo $v['status'] == 1 ? '领取':'未领取';?></td>
                        <td><?php echo long2ip($v['ip'])?></td>
                    </tr>
                    <?php endforeach;?>
                    <?php else:?>
                    <tr role='row' class='odd'>
                        <td colspan="6" style="text-align:center;" >暂无邀请记录</td>
                    </tr>
                    <?php endif;?>
                </tbody>
            </table>
            <?php include_once VIEW_COMMON."page.php"; ?>
        </div>
    </div>
</div>
<footer><hr></footer>
</body>

</html>

<script src="/js/jquery.form.js"></script>
<script type="text/javascript" src="/js/bootstrap.minv3.js"></script>
<script type="text/javascript" src="/js/bootstrap-dialog.min.js"></script>
<script type="text/javascript" src="/js/main.js"></script>
<script type="text/javascript" src="/js/date.js"></script>

<script type="text/javascript">
    function deletprop(){
        $(this).parents('p').remove();
    }
    
    window.table_reload = function () {
        $('input[aria-controls=example][type=search]').focus();
        table.reload();
    };
        
    function setActive() {
        var msg_id = $(this).parents('tr').data('data-id');
        var status = $(this).attr('rel');
        $.post('system/goods/active', {
            goods_id: msg_id,
            status: status
        }, function (json) {
            if (json.result == 0) {
                showMsg('修改成功', function(){
                    window.location.reload();
                });
            } else {
                showMsg(json.msg, true);
            }
        }, 'json');
    }
    
    function downAction() {
        doPost('/gamemt/active/update', {'status':0});
    }
    
    function deleteAction() {
        doPost('/gamemt/active/delete');
    }
    
    function upAction() {
        doPost('/gamemt/active/update', {'status':1});
    }
    
    function doPost(url, params={}){
        var list = [];
        $('input[name=line-check]:checked').each(function () {
            list.push(this.value);
        });
        if (list.length == 0) {
            showMsg("请选择要操作的选项", true);
            return;
        }
        params['id'] = list;
        $.post(url, params, function (json) {
            if (json.result == 0) {
                showMsg('修改成功', function(){
                    window.location.reload();
                });
            } else {
                showMsg(json.msg, true);
            }
        }, 'json');
    }
</script>