<?php

return array(
//    'MANAGE'            =>'管理首页',
//    'MANAGE.MANAGE'      =>['管理首页','manage_index.html'],
//    'MANAGE.INFOR'       =>['基本信息','information.html'],
    //=======================================================
    'PLAYER'            => '游戏玩家',
    'PLAYER.USER'       => ['用户管理', 'user.html'],
    'PLAYER.ZICHAN'     => ['资产管理',''],
    'PLAYER.ONLINE'   => ['在线列表', 'onlinelist.html'],

    'PLAYER.GOLD'       => ['金币管理', 'money.html'],
//    'PLAYER.GGIVE'      => ['金币流水记录', 'player_Goldpre.html'],
//    'PLAYER.DGIVE'      => ['钻石流水记录', 'Player_Diamondpre.html'],
    'PLAYER.GAMERECOURD'     => ['游戏记录', 'game.html'],
 //   'PLAYER.WINORLOSE'       => ['输赢排行耪', 'winorlose.html'],
  //  'PLAYER.POPULARITY'       => ['人气排行耪', 'popularity.html'],
 //   'PLAYER.SORTPOPULARITY'       => ['赠送人气排行耪', 'popusort.html'],
//    'PLAYER.BANK'       => ['银行记录', 'Player_Bank.html'],
    //'PLAYER.PRE'        => ['赠送记录','player_pre.html'],
//    'PLAYER.MGIVE'      => ['赠送会员记录', 'Player_Memberpre.html'],
//    'PLAYER.POPULARITY' => '人气排行榜',
//    'PLAYER.GIFTLOG'    => ['赠送礼物记录','Player_Giftlog.html'],
//    'PLAYER.CLEAR'      => ['清零逃跑率', 'Player_Clearlog.html'],
//    'PLAYER.EXPLOITE'   => ['比赛战绩', 'gamewinlose.html'],
//    'PLAYER.CLIMIT'     => ['限制游戏聊天', 'Player_Charlimit.html'],
    'PLAYER.BANIP'     => ['限制IP', 'Player_Banip.html'],
    //'PLAYER.PHONEBLACK'   => ['黑名单', 'Player_Phoneblack.html'],
    //'PLAYER.PHONEBLACK1'   => ['白名单', 'Player_white.html'],
  //  'PLAYER.PHONEVC' => ['手机短信', 'player/phonevc/list'],

    //=======================================================
    'RECHARGE'               => '交易管理',
//    'RECHARGE.RECHAR'       => ['充值','recharge.html'],
    'RECHARGE.RCSTAT'       => ['充值日报查询', 'Recharge_Rcstat.html'],
//    'RECHARGE.RELOG'        => ['充值记录', 'Recharge_Rclog.html'],
    'RECHARGE.ORDER'        => ['充值记录', 'orders.html'],
//    'RECHARGE.GLODLOG'      => ['金币交易明细', 'Recharge_Goldlog.html'],
//    'RECHARGE.WITHDRAW'     => ['提现审核列表', 'Recharge_Withdrawlog.html'],
//    'RECHARGE.RECHARSET'     => ['充值设置', 'recharge_set.html'],
//    'RECHARGE.STORE'        => ['库存统计', 'sum.html'],
    //=======================================================
    'GAMEMT'             => '游戏维护',
    'GAMEMT.GAMETYPE'       => ['游戏类型', 'gamemt_Gametype.html'],
    'GAMEMT.GAMEMODE'       => ['游戏模式', 'gamemt_Gamemode.html'],
 //   'GAMEMT.ROOM'       => ['牛牛控制', 'gamemt_Room.html'],
  //  'GAMEMT.ROOM21'       => ['21点控制', 'gamemt_rooms.html'],
    'GAMEMT.ROOMF'       => ['捕鱼控制', 'gamemt_roomf.html'],
//    'GAMEMT.CAROUSEL'       => ['轮播图管理', 'gamemt_Carousel.html'],
//    'GAMEMT.HORSEMSG'   => ['跑马灯管理', 'gamemt_Horsemsg.html'],
//    'GAMEMT.SYSSET'   => ['系统设置', 'gamemt_sysset.html'],
    'GAMEMT.MODEL'   => ['模块状态', 'gamemt/model/list'],
    'GAMEMT.ACTIVITY'   => ['活动管理', 'gamemt/activity/list'],
    'GAMEMT.EMAIL'   => ['邮件', 'gamemt/email/list'],
    'GAMEMT.BROADCAST'   => ['广播', 'gamemt/broadcast/list'],
    'GAMEMT.SENSITIVE'   => ['敏感字', 'gamemt/sensitive/list'],
 //   'GAMEMT.GIFT'   => ['礼物管理', 'gamemt/gift/list'],
    'GAMEMT.TASK'   => ['任务管理', 'gamemt/task/list'],
    'GAMEMT.ONLINE'   => ['在线奖励管理', 'gamemt/online/edit'],
    'GAMEMT.VIP'   => ['VIP和签到管理', 'gamemt/vip/list'],
//    'GAMEMT.PACKAGE'   => ['首次充值礼包管理', 'gamemt/package/list'],
    'GAMEMT.FISH'   => ['捕鱼鱼种管理', 'gamemt/fish/list'],
    'GAMEMT.FISH1'   => ['捕鱼调控系数', 'gamemt/fish/coefficient'],
    //'GAMEMT.INVITE'     => ['分享管理', 'gamemt_Invite.html'],
//    'GAMEMT.ITEM'       => ['道具管理', 'props_manager.html'],
    'GAMEMT.GOODS'      => ['商城管理', 'good_manager.html'],
    'GAMEMT.FEEDBACK'   => ['反馈管理', 'feedback.html'],
    'GAMEMT.NOTICE'     => ['公告管理', 'gamemt/notice/list'],
    'GAMEMT.VERSION'    => ['版本设置', 'gamemt/version/index'],
    'GAMEMT.ARENA'    => ['竞技场设置', 'arena_manager.html'],
//    'GAMEMT.ACTIVE'     => ['活动管理', 'gamemt/active/list'],
//    'GAMEMT.SHARE'     => ['分享管理', 'gamemt/share/list'],
//    'GAMEMT.TEM'        => ['模板样式', 'gamemt_tem.html'],
    //=======================================================
//    'SYS'           => '系统维护',
//    'SYS.MSG'       => ['系统消息', 'sysadmin.html'],
//    'SYS.EXCHANGE'  => ['兑换管理', 'duihuan.html'],
//    'SYS.EXPAND'    => ['推广统计', 'tuiguang.html'],
//     'SYS.ACTIVE'    => ['活动公告', 'newsgg.html'],
    //=======================================================
//    'WEB'           => '网站系统',
//    'WEB.NEWS'      => ['新闻管理', 'news.html'],
//    'WEB.BROADCAST' => ['公告管理', 'newsggmanage.html'],
//    'WEB.RULE'      => ['规则管理', 'rules.html'],

    //=======================================================
    'ADMIN'         => '后台系统',
    'ADMIN.USER'    => ['后台账号管理', 'admin.html'],
//    'ADMIN.CHANNEL'    => ['渠道管理', 'admin_Channel.html'],
    'ADMIN.ROLE'    => ['角色管理', 'juese.html'],
    'ADMIN.CLEAN'    => ['数据清理', 'clean.html'],
    //=======================================================
//    'LOG'           => '操作日志',
    //=======================================================
    'SYSTEM'           => '数据统计',
    'SYSTEM.STAT'   => ['用户统计', 'gamemt/statistics/user'],
    'SYSTEM.LOGINLOG' =>['登录账户库存记录','loginlog.html'],
//    'SYSTEM.STAT1'   => ['活跃统计', 'gamemt/statistics/active'],
    //'SYSTEM.ONLINE'   => ['在线统计', 'online.html'],
    'SYSTEM.STAT2'   => ['存量统计', 'gamemt/statistics/estate?type=seven'],
    'SYSTEM.GOLD'    => ['金币报表', 'gold_count.html'],

    'SYSTEM.SAFELOG' => ['保险箱流水','safe_log.html'],
    'SYSTEM.EMERALD' => ['绿宝石流水','emerald.html'],
    'SYSTEM.CREATELOG' => ['钻石流水','credit_log.html'],
	'SYSTEM.POINTLOG' => ['积分兑换','point_log.html'],
//    'SYSTEM.RENQI'  =>['人气兑换流水','renqi.html'],
    'SYSTEM.GOLDSTREAM'=>['金币流水','gold_stream.html'],
    'SYSTEM.STAT3'    => ['房间统计', 'homenum.html'],
    'SYSTEM.STAT4' => ['综合统计', 'zonghenum.html'],
    'SYSTEM.SAFE'      => ['安全日志', 'anquan.html'],
	
//    'STATIS.SURVEY'      => ['游戏概况', 'gamesta.html'],
//    'STATIS.STATE'      => ['用户动态', 'userstate.html'],


);
