<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <title>代码生成</title>
        <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

    </head>

    <body class="" style="background: #FFFFFF;">
        <form action="<?=$action?>">
        <div>module     name: <input name="module" style="width:120px;"/></div>
        <div>controller name: <input name="controller" style="width:120px;"/></div>
            <div>table      name: <input name="table_name" style="width:120px;"/></div>
        <div>model      name: <input name="model" style="width:120px;"/></div>
        <input type="submit" value="生成代码">
        </form>
    </body>

</html>