<?php include_once VIEW_COMMON."header.php"; ?>
<div class="main-container" id="main-container" style="margin-left: 0px;">
    <div class="main-container-inner">
        <div class="main-content">
        <div class="page-content">
            <div class="row">
                <div class="col-xs-12">
                    <form class="form-horizontal" id="form">
                        <input type="hidden" id="id" value="<?php echo $info ? $info['id'] : 0?>">
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">公告标题：</label>
                            <div class="col-sm-10">
                                <input type="text" id="title" name="title" 
                                       class="col-xs-10 col-sm-5" value='<?php echo $info ? $info['title'] : ''?>'>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">公告图片：</label>
                            <div class="col-sm-10">
                                <?php if($info):?>
                                <img src="<?php echo $info['images']?>" class="image"  style="max-height:100px;" />
                                <?php else:?>
                                <img src="/files/official.jpg" class="image"  style="max-height:100px;" />
                                <?php endif;?>
                                <button class="btn btn-info inimage" type="button">选择图片</button>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">公告内容：</label>
                            <div class="col-sm-10">
                                <textarea id="content" style="height: 300px;" name="content" class="col-xs-10 col-sm-5"><?php echo $info ? $info['content'] : ''?></textarea>
                            </div>
                        </div>

                        <div class="form-group hidden">
                            <label class="col-sm-2 control-label no-padding-right">发布时间：</label>
                            <div class="col-sm-10">
                                <label>
                                    <input name="times" type="radio" value="0" class="ace" checked="checked"/>
                                    <span class="lbl">立即</span>
                                </label>
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <label>
                                    <input name="times" type="radio" value="1" class="ace" >
                                    <span class="lbl">定时</span>
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                                <i class="icon-calendar bigger-110"></i>
                                        </span>
                                        <input class="col-sm-3" type="text" name="avttime" id="avttime" value="" readonly>
                                    </div>
                                </label>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">公告属性：</label>
                            <div class="col-sm-10">
                                <label>
                                    <input name="attribute" type="radio" value="0" class="ace" checked="checked"/>
                                    <span class="lbl">普通</span>
                                </label>
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <label>
                                    <input name="attribute" type="radio" value="1" 
                                           class="ace" <?php echo $info && $info['attribute'] == 1 ? 'checked':''?>>
                                    <span class="lbl">限时</span>
                                </label>
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <label>
                                    <input name="attribute" type="radio" value="2" 
                                           class="ace" <?php echo $info && $info['attribute'] == 1 ? 'checked':''?>>
                                    <span class="lbl">总置顶</span>
                                </label>
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <label>
                                    <input name="attribute" type="radio" value="3" 
                                           class="ace" <?php echo $info && $info['attribute'] == 3 ? 'checked':''?>>
                                    <span class="lbl">推荐</span>
                                </label>
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <label>
                                    <input name="attribute" type="radio" value="4" 
                                           class="ace" <?php echo $info && $info['attribute'] == 4 ? 'checked':''?>>
                                    <span class="lbl">热门</span>
                                </label>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button class="btn btn-primary" type="submit" id="save">
                                    <i class="icon-ok"></i>
                                    保存
                                </button>
                                <a class="btn" href="javascript:history.go(-1);">
                                    <i class="icon-undo"></i>
                                    取消
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
<?php include_once VIEW_COMMON."footer.php"; ?>
<link rel="stylesheet" href="/skin/umeditor/themes/default/css/umeditor.css" />
<script src="/skin/umeditor/umeditor.config.js"></script>
<script src="/skin/umeditor/umeditor.min.js"></script>
<script src="/skin/js/jquery.validate.min.js"></script>
<link rel="stylesheet" href="/skin/css/daterangepicker.css" />
<script src="/skin/js/moment.min.js"></script>
<script src="/skin/js/daterangepicker.min.js"></script>
<script type="text/javascript">
    $(function () {
        var cnt = UM.getEditor('editer', ace.editorConfig);
        $('#avttime').daterangepicker({
            singleDatePicker: true,
            timePicker: !0,
            format: "YYYY/MM/DD HH:mm"
        });
        $('.inimage').InsertImage();
        $("#form").validate({
            rules: {
                title: {
                    required: true
                },
                content: {
                    required: true
                }
            },
            messages: {
                title: {
                    required: '请输入公告标题'
                },
                content: {
                    required: '请输入公告内容'
                }
            },
            errorElement: "span",
            highlight: function (element, errorClass, validClass) {
                $(element).parents('.form-group').addClass('has-error');
            },
            unhighlight: function (element, errorClass, validClass) {
                $(element).parents('.form-group').removeClass('has-error');
            },
            submitHandler: function (form)
            {
                var params = {
                    'id': $('#id').val(),
                    'title': $('#title').val(),
                    'content': $('#content').val(),
                    'times': $("input[name='times']:checked").val(),
                    'attribute': $("input[name='attribute']:checked").val(),
                    'images': $('.image').attr('src'),
                    'start_time':$('#avttime').val()
                };
                $('#save').html('<i class="icon-ok"></i>保存中...').attr('disabled', 'true');
                $.ajax({
                    type: "POST",
                    url: "/gamemt/notice/save",
                    data: params,
                    dataType: "json",
                    success: function (msg) {
                        $('#save').html('<i class="icon-ok"></i> 保存').removeAttr('disabled');
                        if (msg.result == 0) {
                            showMsg("成功", function () {
                                history.go(-1);
                            });
                        } else {
                            showMsg(msg.message, true);
                        }
                    }
                });
            }
        });
    })
</script>