<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>礼物管理</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/css/theme.css">
    <link rel="stylesheet" type="text/css" href="/css/main.css">
    <link rel="stylesheet" type="text/css" href="/css/tables.css" />
    <script type="text/javascript" src="/js/jquery.js"></script>
    <script type="text/javascript" src="/js/bootstrap.js"></script>
    <script type="text/javascript" src="/js/j.dt.min.js"></script>
    <script type="text/javascript" src="/js/moment.js"></script>
    <script type="text/javascript" src="/js/mos.js"></script>
    <script src="/skin/js/bootbox.min.js"></script>
    <style>
        table#tab input,table#tab textarea{
            margin-top:5px;
        }
        table#tab td{ height: 70px;text-align: left !important;}
        table#tab .pad-l{padding-left:30px;}
        table#tab .sel{float:left; border-radius:0px; margin-bottom:5px; max-width:200px; margin-right:30px;}
        table#tab .wid{width:100px; margin:0 10px 5px 0; float:left; vertical-align:middle;}
        table#tab .delspan{cursor:pointer; font-size:12px; font-weight:normal;}
        table#tab td.seltd{ border: 1px solid #ccc;}
        table#tab div.box{ max-height:150px; overflow-y:auto; padding:10px 0 5px 10px;}
        table#tab span.inser{border: 1px solid #ccc; font-size:12px; padding:3px 10px; float:right; cursor:pointer;}
        table#tab textarea.tex{ height:70px; line-height:20px;  padding:5px 7px; resize:none; border-radius:0px;}
        .theadtbody{text-align: left !important;}
        .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td{
            vertical-align: text-bottom !important;
        }
    </style>
</head>

<body class="" style="background: #FFFFFF;">
<div class="header">
    <h1 class="page-title">礼物管理</h1>
</div>
<ul id="myTab" class="nav nav-tabs">
    <li>
        <a href="/gamemt/gift/list">礼物管理</a>
    </li>
    <li class="active">
        <a href="/gamemt/gift/info">兑换配置</a>
    </li>
</ul>
    <div class="tab-pane fade in active" id="User">
        <form class="form-horizontal" role="form">
            <fieldset>
                <div class="form-group">
                    <label class="col-sm-1 control-label" for="">兑换比例配置:</label>
                    <div class="col-sm-2">
                        <input class="form-control" id="exchange" type="text" value="<?php echo $info ? $info['exchange'] : "";?>">
                    </div>
                </div>
            </fieldset>
        </form>
        <div class="form-group">
            <label class="col-sm-1 control-label" for=""></label>
            <div class="col-sm-2">
                <input type="submit" id="btnsave" value="点击保存" class="">
            </div>
        </div>
    </div>
<footer><hr></footer>
</body>

</html>

<script src="/js/jquery.form.js"></script>
<script type="text/javascript" src="/js/bootstrap.minv3.js"></script>
<script type="text/javascript" src="/js/bootstrap-dialog.min.js"></script>
<script type="text/javascript" src="/js/main.js"></script>
<script type="text/javascript" src="/js/date.js"></script>

<script type="text/javascript"> 
    $("#btnsave").click(function(){
        if ($("#exchange").val() == ""){
            showMsg("请输入要兑换的比例值", true);return;
        }
        $.post('/gamemt/gift/setInfo', {'exchange':$("#exchange").val()}, function (json) {
            if (json.result == 0) {
                showMsg('重置成功');
            } else {
                showMsg(json.msg, true);
            }
        }, 'json');
    });
</script>