<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>礼物管理</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/css/theme.css">
    <link rel="stylesheet" type="text/css" href="/css/main.css">
    <link rel="stylesheet" type="text/css" href="/css/tables.css" />
    <script type="text/javascript" src="/js/jquery.js"></script>
    <script type="text/javascript" src="/js/bootstrap.js"></script>
    <script type="text/javascript" src="/js/j.dt.min.js"></script>
    <script type="text/javascript" src="/js/moment.js"></script>
    <script type="text/javascript" src="/js/mos.js"></script>
    <script src="/skin/js/bootbox.min.js"></script>
    <style>
        table#tab input,table#tab textarea{
            margin-top:5px;
        }
        table#tab td{ height: 70px;text-align: left !important;}
        table#tab .pad-l{padding-left:30px;}
        table#tab .sel{float:left; border-radius:0px; margin-bottom:5px; max-width:200px; margin-right:30px;}
        table#tab .wid{width:100px; margin:0 10px 5px 0; float:left; vertical-align:middle;}
        table#tab .delspan{cursor:pointer; font-size:12px; font-weight:normal;}
        table#tab td.seltd{ border: 1px solid #ccc;}
        table#tab div.box{ max-height:150px; overflow-y:auto; padding:10px 0 5px 10px;}
        table#tab span.inser{border: 1px solid #ccc; font-size:12px; padding:3px 10px; float:right; cursor:pointer;}
        table#tab textarea.tex{ height:70px; line-height:20px;  padding:5px 7px; resize:none; border-radius:0px;}
        .theadtbody{text-align: left !important;}
        .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td{
            vertical-align: text-bottom !important;
        }
    </style>
</head>

<body class="" style="background: #FFFFFF;">
<div class="header">
    <h1 class="page-title">礼物管理</h1>
</div>
<ul id="myTab" class="nav nav-tabs">
    <li class="active">
        <a href="/gamemt/gift/list">礼物管理</a>
    </li>
    <li>
        <a href="/gamemt/gift/info">兑换配置</a>
    </li>
</ul>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="block span6 dataTables_wrapper">
            <table class="table display block-body collapse in" id="example">
                <input type="button" name="btnadd" id="btnadd" onclick="window.location.reload()" class="input_btn_h input-table" value="刷新" />
                <input type="button" name="btnadd" id="btnadd" onclick="window.location.href='/gamemt/gift/edit'" class="input_btn_h input-table" value="新增" />
                <input type="button" name="btndelete" id="btndelete" class="input_btn_h input-table" value="删除" data-ctrl-btn="deleteAction"/>
                <input type="button" name="btndelete" id="btndOn" class="input_btn_h input-table" value="上线" data-ctrl-btn="upAction"/>
                <input type="button" name="btndelete" id="btndDown" class="input_btn_h input-table" value="下线" data-ctrl-btn="downAction"/>
                <input type="button" name="btndelete" id="btndDown" class="input_btn_h input-table" value="重置缓存" data-ctrl-btn="resetAction"/>
                <thead class="theadtbody">
                    <tr>
                        <th><input type="checkbox" id="checkAll" onclick="check_all();"></th>
                        <th>排序</th>
                        <th>图片icon</th>
                        <th>礼物名称</th>
                        <th>礼物单位</th>
                        <th>类型值</th>
                        <th>金币价格</th>
                        <th>人气值</th>
                        <th>状态</th>
                        <th>管理</th>
                    </tr>
                </thead>
                <tbody class="theadtbody">
                    <?php if($list):?>
                    <?php foreach ($list as $k=>$v):?>
                    <tr role='row' class='odd'>
                        <td><input type='checkbox' name='line-check' class='check' value='<?php echo $v['id']?>'></td>
                        <td><?php echo $v['g_sort']?></td>
                        <td><img src="<?php echo $v['icon']?>" style="width:80px;"></td>
                        <td><?php echo $v['name']?></td>
                        <td><?php echo $v['unit']?></td>
                        <td><?php echo $v['g_type']?></td>
                        <td><?php echo $v['gold']?></td>
                        <td><?php echo $v['popularity']?></td>
                        <td><?php echo $v['status'] == 1 ? '上线':'下线';?></td>
                        <td>
                            <button data-ctrl-btn="editAction" onclick="window.location.href='/gamemt/gift/edit?id=<?php echo $v['id'];?>'">编辑</button>
                        </td>
                    </tr>
                    <?php endforeach;?>
                    <?php else:?>
                    <tr role='row' class='odd'>
                        <td colspan="10" style="text-align:center;" >暂无信息</td>
                    </tr>
                    <?php endif;?>
                </tbody>
            </table>
            <?php include_once VIEW_COMMON."page.php"; ?>
        </div>
    </div>
</div>
<footer><hr></footer>
</body>

</html>

<script src="/js/jquery.form.js"></script>
<script type="text/javascript" src="/js/bootstrap.minv3.js"></script>
<script type="text/javascript" src="/js/bootstrap-dialog.min.js"></script>
<script type="text/javascript" src="/js/main.js"></script>
<script type="text/javascript" src="/js/date.js"></script>

<script type="text/javascript">
    function deletprop(){
        $(this).parents('p').remove();
    }
    
    window.table_reload = function () {
        $('input[aria-controls=example][type=search]').focus();
        table.reload();
    };
    
    function setActive() {
        var msg_id = $(this).parents('tr').data('data-id');
        var status = $(this).attr('rel');
        $.post('system/goods/active', {
            goods_id: msg_id,
            status: status
        }, function (json) {
            if (json.result == 0) {
                showMsg('修改成功', function(){
                    window.location.reload();
                });
            } else {
                showMsg(json.msg, true);
            }
        }, 'json');
    }
    
    function resetAction() {
        $.post('/gamemt/gift/reset', {}, function (json) {
            if (json.result == 0) {
                showMsg('重置成功');
            } else {
                showMsg(json.msg, true);
            }
        }, 'json');
    }
    
    function downAction() {
        doPost('/gamemt/gift/update', {'status':0});
    }
    
    function deleteAction() {
        doPost('/gamemt/gift/delete');
    }
    
    function upAction() {
        doPost('/gamemt/gift/update', {'status':1});
    }
    
    function doPost(url, params={}){
        var list = [];
        $('input[name=line-check]:checked').each(function () {
            list.push(this.value);
        });
        if (list.length == 0) {
            showMsg("请选择要操作的选项", true);
            return;
        }
        params['id'] = list;
        $.post(url, params, function (json) {
            if (json.result == 0) {
                showMsg('修改成功', function(){
                    window.location.reload();
                });
            } else {
                showMsg(json.msg, true);
            }
        }, 'json');
    }
</script>